name: "Hello Action"
description: "A simple hello world action"
inputs:
  name:
    description: "Name to greet"
    required: false
    default: "World"
  runs:
    using: "node20"
    main: "index.js"  